### ISSUE TITLE
error with kdeconnect-ring

### ISSUE THREAD

**Issue by robstewart57** [carldotac/kdeconnect.el#1]
When I try run this command in the `*Messages*` buffer I get:

```
wrong-type-argument arrayp nil
```

And if I set `debug-on-error` to `t` and then run the command, in the `*Backtrace*` buffer I get:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
  shell-quote-argument(nil)
  kdeconnect-ring()
  call-interactively(kdeconnect-ring record nil)
  command-execute(kdeconnect-ring record)
  execute-extended-command(nil "kdeconnect-ring")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by carldotac** [comment]
Is it just kdeconnect-ring? Does kdeconnect-ping, for example, work?

I have replicated this error message by calling kdeconnect-ring without setting kdeconnect-active-device (as opposed to kdeconnect-devices--I think I will update the documentation to clarify the difference and importance of setting both). Have you set kdeconnect-active-device via your init.el or by calling kdeconnect-select-active-device?

**Comment by robstewart57** [comment]
Ah, I had forgotten to set kdeconnect-active-device. I tried `kdeconnect-select-active-device`: 

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("," nil 0)
  split-string(nil "," t)
  (completing-read "Select a device: " (split-string kdeconnect-devices "," t) nil t "")
  (list (completing-read "Select a device: " (split-string kdeconnect-devices "," t) nil t ""))
  call-interactively(kdeconnect-select-active-device record nil)
  command-execute(kdeconnect-select-active-device record)
  execute-extended-command(nil "kdeconnect-select-active-device")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

However, setting it manually does the trick:

``` elisp
(setq kdeconnect-devices "<device ID>")
(setq kdeconnect-active-device "<device ID")
```

Now `kdeconnect-ring` works.

**Comment by carldotac** [comment]
Thanks for the confirmation! I recognize that setting up kdeconnect-devices in `init.el` and kdeconnect-active-device in `init.el` or via `kdeconnect-select-active-device` might be a little much for one-device workflow. I originally parsed the shell output of `kdeconnect-cli -a --id-only` and only required an active device variable, but there were edge cases without good solutions, and pre-declaring devices makes switching faster anyway.

I've updated the readme to help avoid any such confusion in the future.

**Comment by robstewart57** [comment]
Thanks @carldotac , a great project that I intend to try out for a few weeks at least :+1:
