### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [carldotac/kdeconnect.el#7]
How can i send a directory ?

**Comment by carldotac** [comment]
This isn't something that KDE Connect itself supports. It would not be too difficult to write Elisp to send multiple files at once, but kdeconnect-cli doesn't allow for creating directories or subdirectories on the target device. I know in Dolphin on KDE, I'm able to create and copy folders on a phone connected by KDE Connect. But even though right-clicking a file gives a context menu option to send a file via KDE Connect, right-clicking a folder does not.
I have two suggestions that are not mutually exclusive. The first is to create a wish at [bugs.kde.org](https://bugs.kde.org/) for the ability to send directories. If that functionality were added to kdeconnect-cli, it would be easy to add to kdeconnect.el. The other is the easiest workaround: compress the directory and send the file to your other device.
